[project]
name = "stock-market-mcp-server"
version = "0.1.0"
description = "An MCP to provide information about the stock market"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.2.7",
    "mcp[cli]>=1.7.1",
    "yfinance>=0.2.41",
    "python-dotenv>=1.0.1",
]
